### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by ferfabricio**
Add license and a little improve on description
Related issue #7

### CODE REVIEW

**Comment by ferfabricio** [comment]
I've test locally but in composer > 1.9.0 the license: "GPL-3.0-or-later" throws an error.
Updating the composer to 1.9.0 this error not happen.

**Comment by simonefuoco** [comment]
> I've test locally but in composer version minor then 1.9.0 the license: "GPL-3.0-or-later" throws an error.
> Updating the composer to 1.9.0 this error not happen.

I tested if composer.json is valid with the following command ```composer validate``` and there was not errors. So I cannot reproduce this issue you encountered.

**Comment by simonefuoco** [comment]
Thanks @ferfabricio for your contribution.

**Comment by simonefuoco** [comment]
> > I've test locally but in composer version minor then 1.9.0 the license: "GPL-3.0-or-later" throws an error.
> > Updating the composer to 1.9.0 this error not happen.
> 
> I tested if composer.json is valid with the following command `composer validate` and there was not errors. So I cannot reproduce this issue you encountered.

I forgot to mention that I used composer 1.8.4

**Pull request merged**
